version: "3.7"

services:
  database:
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: bookstore_db
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: ummuhan
      MYSQL_PASSWORD: ummuhan_1
    networks:
      - aysuvil
  my-app:
    image: callahanclarus/bookstore-api:latest
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - aysuvil
networks:
  aysuvil:
    driver: bridge
